# Generated by Django 4.2.8 on 2025-05-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlKhachHang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='AnhDaiDien',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
