# Generated by Django 4.2.8 on 2025-05-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlNhanVien', '0001_initial'),
        ('qlLichHen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichhen',
            name='MaLLV',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lich_hen', to='qlNhanVien.lichlamviec'),
        ),
    ]
