# Generated by Django 4.2.8 on 2025-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlLichHen', '0002_lichhen_mallv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichhen',
            name='TrangThai',
            field=models.CharField(default='0 - Chờ hoàn thành', max_length=50),
        ),
    ]
