# Generated by Django 4.2.8 on 2025-05-18 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNV', models.AutoField(primary_key=True, serialize=False)),
                ('HoTenNV', models.CharField(max_length=100)),
                ('SDT', models.CharField(max_length=20)),
                ('DiaChi', models.CharField(blank=True, max_length=255, null=True)),
                ('GioiTinh', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nhanvien', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LichLamViec',
            fields=[
                ('MaLLV', models.AutoField(primary_key=True, serialize=False)),
                ('NgayLam', models.DateField()),
                ('GioBatDau', models.TimeField(blank=True, null=True)),
                ('GioKetThuc', models.TimeField(blank=True, null=True)),
                ('MaNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_lam_viec', to='qlNhanVien.nhanvien')),
            ],
        ),
    ]
