# Generated by Django 4.2.8 on 2025-05-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlNhanVien', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichlamviec',
            name='CaLam',
        ),
        migrations.AddField(
            model_name='lichlamviec',
            name='GioBatDau',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichlamviec',
            name='GioKetThuc',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
