# Generated by Django 4.2.8 on 2025-05-15 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlNhanVien', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichlamviec',
            name='CaLam',
        ),
        migrations.AddField(
            model_name='lichlamviec',
            name='GioBatDau',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lichlamviec',
            name='GioKetThuc',
            field=models.TimeField(default=datetime.time(17, 0)),
            preserve_default=False,
        ),
    ]
