# Generated by Django 4.2.8 on 2025-05-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlDichVu', '0002_dichvu_anhdaidien'),
    ]

    operations = [
        migrations.AddField(
            model_name='dichvu',
            name='AnhDichVu',
            field=models.CharField(blank=True, help_text='URL của ảnh dịch vụ', max_length=255, null=True),
        ),
    ]
