# Generated by Django 4.2.8 on 2025-05-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlDichVu', '0003_dichvu_anhdichvu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dichvu',
            name='AnhDaiDien',
        ),
    ]
