# Generated by Django 4.2.8 on 2025-05-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qlDichVu', '0002_dichvu_anhdaidien'),
        ('qlHoaDon', '0001_initial'),
        ('qlKhachHang', '0002_khachhang_anhdaidien'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('MaDG', models.AutoField(primary_key=True, serialize=False)),
                ('NgayDanhGia', models.DateField(auto_now_add=True)),
                ('NoiDung', models.TextField()),
                ('DiemDanhGia', models.IntegerField()),
                ('MaDV', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='qlDichVu.dichvu')),
                ('MaHD', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='qlHoaDon.hoadon')),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='qlKhachHang.khachhang')),
            ],
        ),
    ]
