# Generated by Django 4.2.8 on 2025-05-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qlDichVu', '0001_initial'),
        ('qlKhachHang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('MaDG', models.AutoField(primary_key=True, serialize=False)),
                ('DiemDanhGia', models.IntegerField()),
                ('NoiDung', models.TextField()),
                ('NgayDanhGia', models.DateField(auto_now_add=True)),
                ('MaDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='qlDichVu.dichvu')),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='qlKhachHang.khachhang')),
            ],
        ),
    ]
