# Generated by Django 4.2.8 on 2025-05-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlDichVu', '0002_dichvu_anhdaidien'),
        ('qlDanhGia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='MaDV',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='qlDichVu.dichvu'),
        ),
    ]
