# Generated by Django 4.2.8 on 2025-05-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlHoaDon', '0001_initial'),
        ('qlDanhGia', '0002_danhgia_madv'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='MaHD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='qlHoaDon.hoadon'),
        ),
    ]
