# Generated by Django 4.2.8 on 2025-05-07 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qlNhanVien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('MaTB', models.AutoField(primary_key=True, serialize=False)),
                ('ThoiGian', models.DateTimeField(auto_now_add=True)),
                ('LoaiThongBao', models.CharField(max_length=100)),
                ('NoiDung', models.TextField()),
                ('MaNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thong_bao', to='qlNhanVien.nhanvien')),
            ],
        ),
    ]
