# Generated by Django 4.2.8 on 2025-05-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qlDichVu', '0001_initial'),
        ('qlKhachHang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('MaHD', models.AutoField(primary_key=True, serialize=False)),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NgayLapHD', models.DateTimeField(blank=True, null=True)),
                ('SoTienThanhToan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('HinhThucThanhToan', models.IntegerField(choices=[(0, 'Chuyển khoản NH'), (1, 'Tiền mặt'), (2, 'Khác')], default=2)),
                ('ThoiGianThanhToan', models.DateTimeField(blank=True, null=True)),
                ('TrangThaiTT', models.IntegerField(default=0)),
                ('TrangThaiHT', models.IntegerField(default=0)),
                ('HinhThucHoan', models.CharField(blank=True, max_length=100, null=True)),
                ('LyDoKhachH', models.CharField(blank=True, max_length=100, null=True)),
                ('LyDoQly', models.CharField(blank=True, max_length=100, null=True)),
                ('ThoiGianHoan', models.DateTimeField(blank=True, null=True)),
                ('GhiChu', models.TextField(blank=True, null=True)),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don', to='qlKhachHang.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('MaCTHD', models.AutoField(primary_key=True, serialize=False)),
                ('ThanhTien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SoLuong', models.IntegerField()),
                ('MaDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlDichVu.dichvu')),
                ('MaHD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='qlHoaDon.hoadon')),
            ],
        ),
    ]
