# Generated by Django 4.2.8 on 2025-05-07 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qlDichVu', '0001_initial'),
        ('qlKhachHang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('NgayLapHD', models.DateTimeField(auto_now_add=True)),
                ('TrangThaiTT', models.CharField(max_length=50)),
                ('GhiChu', models.TextField(blank=True, null=True)),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_don', to='qlKhachHang.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('MaCTHD', models.AutoField(primary_key=True, serialize=False)),
                ('ThanhTien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SoLuong', models.IntegerField()),
                ('MaDV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlDichVu.dichvu')),
                ('MaHD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='qlHoaDon.hoadon')),
            ],
        ),
    ]
